apiVersion: apps/v1
kind: Deployment
metadata:
  name: logggggg-dep
  labels:
    app: logggggg-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logggggg-dep
  template:
    metadata:
      labels:
        app: logggggg-dep
    spec:
      containers:
        - name: logggggg-dep
          image: gcr.io/$PROJECT_ID/sinmetal/logggggg/master
